#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
version: '3'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
networks:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  hani_nw_200:
    external: true
    
# Remark the (hani_nw_200) was create by command :   
#T_NETWORK='hani_nw_200';docker network rm $T_NETWORK ;docker network create --subnet=192.168.200.0/24 $T_NETWORK ; docker network ls 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
services:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#######################################################################  
  ser_busybox:
#######################################################################  
    image: busybox
    container_name: busybox1
    hostname: busybox1
    networks:
      hani_nw_200:
        ipv4_address: 192.168.200.88 
#   ports:
#     - 1234:1234
#   command: sh -c 'mysql -u root -p mypass123 -e "update user set authentication_string=password(''), plugin='mysql_native_password' where user='root';" '   
#   command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mypass123
      - qMYSQL_USER=user3"
      - qMYSQL_PASSWORD=admin3"
      - qMYSQL_DATABASE=db3      
    volumes:
      - /volumes/busybox:/home/hani
#######################################################################

