#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
version: '3'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
networks:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  hani_nw_200:
    external: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
services:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#######################################################################  
  ser_ssh:
#######################################################################  
    image: hani86400/sshimage7
    container_name: ssh1
    hostname: ssh1
    networks:
      hani_nw_200:
        ipv4_address: 192.168.200.55 
    ports:
      - 20:20
    environment:
      - MYSQL_ROOT_PASSWORD=mypass123
      - qMYSQL_USER=user3"
      - qMYSQL_PASSWORD=admin3"
      - qMYSQL_DATABASE=db3      
#    volumes:
#      - /volumes/mysql/DATA:/var/lib/mysql
#######################################################################
