#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
version: '3'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
networks:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
  hani_nw_200:
    external: true
    
# Remark the (hani_nw_200) was create by command :   
#T_NETWORK='hani_nw_200';docker network rm $T_NETWORK ;docker network create --subnet=192.168.200.0/24 $T_NETWORK ; docker network ls 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
services:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#######################################################################  
  ser_node_exporter:
#######################################################################  
    image: prom/node-exporter:v1.6.0@sha256:4c607459b09ad6bcf4d73986f9060ae6508f789abf85c0c4459809ddf3e1e7a0
    container_name: exporter1
    hostname: exporter1
    networks:
      hani_nw_200:
        ipv4_address: 192.168.200.61 
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
#######################################################################


#######################################################################
  ser_prometheus:
#######################################################################
    image: prom/prometheus:v2.44.0@sha256:6f764183520fcc859ad6bffc6dad937220ae491aea931891e9ffee4d946c0ac3
    container_name: prometheus1
    hostname: prometheus1
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      hani_nw_200:
        ipv4_address: 192.168.200.62
    volumes:
      - type: bind
        source: /volumes/prometheus/conf/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true    
#######################################################################

#######################################################################  
  ser_grafana:
#######################################################################  
    image: grafana/grafana:9.5.2@sha256:2aafd24a138277142a86b6ed43b7537e1ec8226478f5240c459e9330a3461cdb
    container_name: grafana1
    hostname: grafana1
    networks:
      hani_nw_200:
        ipv4_address: 192.168.200.63 
    ports:
      - 3333:3000
    user: grafana   
    volumes:
      - /tmp:/var/lib/grafana
#     - /volumes/grafana/data:/var/lib/grafana      
    environment:
      qqGF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"

#######################################################################


